### ISSUE TITLE
Stack traces show wrong line numbers

### ISSUE THREAD

**Issue by jolampi** [rage/python-editor#106]
The code has to be patched when running normally,  causing line numbers in stack traces to be off by one. They should be parsed to show user correct information.

**Comment by jolampi** [comment]
Running code `print("hello"g)` gives the following error:
```python
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 58, in find_imports
    mod = ast.parse(code)
  File "/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    print("hello"g)
                 ^
SyntaxError: invalid syntax
```

Running code `print("hello"` gives the following error (exposes empty code safeguard `pass` from next line):
```python
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 58, in find_imports
    mod = ast.parse(code)
  File "/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 3
    pass
       ^
SyntaxError: invalid syntax
```
